language: cpp

sudo: required
dist: trusty

notifications: 
  email:
    recipients:
    - rncbc@rncbc.org
    on_success: change
    on_failure: always

branches:
  only:
  - master

before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo apt-get update -qq

install:
- sudo apt-get install -qq libjack-dev
- sudo apt-get install -qq libasio-dev

before_script:
- git submodule update --init

script:
- make CCFLAGS=-std=c++11
