language: cpp

sudo: required
dist: trusty

notifications: 
  email:
    recipients:
    - rncbc@rncbc.org
    on_success: change
    on_failure: always

branches:
  only:
  - master

before_install:
- sudo apt-get update -qq

install:
- sudo apt-get install -qq libjack-dev

script:
- make
- sudo make install
